version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-mq-dotnet
    hostname: my-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672" 
      - "15672:15672"